name: Yocto Build
 
on:
  workflow_dispatch:
 
jobs:
  test:
    runs-on: [self-hosted, linux, x64]  # or add your runner label if custom
    steps:
      - name: Checkout repository
        run: |
          echo "hello aadvait from runnner !"
          pwd 
          ls -l
