name: Yocto Build
 
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: [cariad-yocto, linux, x64]  # or add your runner label if custom
    steps:
      - name: Checkout repository
        run: |
          eco "hello aadvait from runnner !"
          pwd 
          ls -l
