name: Yocto Build
 
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: [self-hosted, linux, x64]  # or add your runner label if custom
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
 
      - name: Change to Home Directory
        run: |
          echo "Switching to home directory"
          cd ~
          echo "Current directory is: $(pwd)"
          ls -l
 
      - name: Set up Yocto Environment
        run: |
          echo "Setting up Yocto environment"
          cd ~/poky  # Replace this if your poky path is different
          source oe-init-build-env || { echo "Failed to source env"; exit 1; }
          echo "Yocto environment setup complete"
 
      - name: Build Yocto Image
        run: |
          echo "Starting BitBake build"
          cd ~/poky/build  # Adjust if your build dir is different
          bitbake core-image-minimal || { echo "BitBake failed"; exit 1; }
          echo "BitBake build completed"
 
      - name: Compress image artifacts
        run: |
          echo "Compressing image outputs..."
          cd ~/poky/build/tmp/deploy/images
          tar -czvf ~/images.tar.gz . || { echo "Compression failed"; exit 1; }
          echo "Compression completed"
 
